spring.application.name=Tontine

# Connexion base de données (valeurs injectées via variables d'environnement)
DATABASE_URL=jdbc:postgresql://dpg-da4g3hc9v7es7383etbg-a/tontine_0and
DATABASE_USERNAME=tontine_0and_user
DATABASE_PASSWORD=9W6JG9joL9kxu4A177cpA1kbPAFm1c5r
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port dynamique fourni par Render
server.port=${PORT:8080}