spring.application.name=Tontine

spring.datasource.url=postgresql://tontine_0and_user:9W6JG9joL9kxu4A177cpA1kbPAFm1c5r@dpg-da4g3hc9v7es7383etbg-a.oregon-postgres.render.com/tontine_0and
spring.datasource.username=tontine_0and_user
spring.datasource.password=9W6JG9joL9kxu4A177cpA1kbPAFm1c5r
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=${PORT:8080}